# PEFT Shortcuts Research Framework - MNLI Multi-Text Field Example
# Configuration for MNLI dataset using premise and hypothesis fields

# Model configuration
model:
  base_model: "microsoft/deberta-v3-base"
  peft_config:
    peft_type: "prompt_tuning"
    peft_args:
      num_virtual_tokens: 20
      task_type: "SEQ_CLS"
      modules_to_save: ["classifier"]

# Basic settings
num_labels: 2 
epochs: 10
lr: 5e-3
seed: 42

outputdir: "outputs/deberta"
# Training dataset with multi-field text configuration
train_dataset:
  name: "nyu-mll/glue"
  config: "qqp"
  batch_size: 32
  is_hf: true
  split: "train"
  text_field: ["question1", "question2"]  # Multi-field configuration for QQP
  label_field: "label"
# Validation datasets
validation_datasets:
  # Clean validation set
  clean:
    name: "nyu-mll/glue"
    config: "qqp"
    batch_size: 32
    is_hf: true
    split: "validation"
    text_field: ["question1", "question2"]  # Same multi-field configuration for QQP
    label_field: "label"
  paws:
    name: "datasets/paws"
    batch_size: 32
    is_hf: false
    split: "validation"
    text_field: ["sentence1", "sentence2"]  # Same multi-field configuration for PAWS
    label_field: "label"

# Training options
tokenizer_max_length: 256 
gradient_accumulation_steps: 1
warmup_ratio: 0.1
save_strategy: "final"
compute_hidden_similarities: false
compute_confidence_metrics: false
metric_for_best_model: "accuracy"

# WandB configuration
wandb:
  project: "qqp-experiments"
  enabled: true 