# PEFT Shortcuts Research Framework - MNLI Multi-Text Field Example
# Configuration for MNLI dataset using premise and hypothesis fields

# Model configuration
model:
  base_model: "meta-llama/Llama-3.2-1B-Instruct"  # Change to your accessible LLAMA model
  peft_config:
    peft_type: "qlora"
    peft_args:
      r: 16
      lora_alpha: 32
      target_modules: ["q_proj", "v_proj", "o_proj"]
      lora_dropout: 0.1
      bias: "none"
      modules_to_save: ["score"]


# Basic settings
num_labels: 2 
epochs: 5
lr: 1e-4
seed: 42

outputdir: "outputs/llama"

# Training dataset with multi-field text configuration
train_dataset:
  name: "nyu-mll/glue"
  config: "qqp"
  batch_size: 32
  is_hf: true
  split: "train"
  text_field: ["question1", "question2"]  # Multi-field configuration for QQP
  label_field: "label"
# Validation datasets
validation_datasets:
  # Clean validation set
  clean:
    name: "nyu-mll/glue"
    config: "qqp"
    batch_size: 32
    is_hf: true
    split: "validation"
    text_field: ["question1", "question2"]  # Same multi-field configuration for QQP
    label_field: "label"
  paws:
    name: "datasets/paws"
    batch_size: 32
    is_hf: false
    split: "validation"
    text_field: ["sentence1", "sentence2"]  # Same multi-field configuration for PAWS
    label_field: "label"


# Training options
tokenizer_max_length: 256 
gradient_accumulation_steps: 1
warmup_ratio: 0.1
save_strategy: "final"

metric_for_best_model: "accuracy"

# WandB configuration
wandb:
  project: "qqp-experiments"
  enabled: true 