model:
  base_model: "meta-llama/Llama-3.2-1B-Instruct" 
  peft_config:
    peft_type: "load_peft"
    peft_args:
      peft_model_path: "dummy_path"

# Basic settings
num_labels: 2
epochs: 5 
lr: 1e-4
seed: 412 

outputdir: "outputs/llama/masktune"

# Training dataset (with poisoning that will be varied)
train_dataset:
  name: "nyu-mll/glue"
  config: "sst2"
  batch_size: 32
  is_hf: true
  split: "train"
  text_field: "sentence"
  label_field: "label"
  poisoning:
    enabled: true
    text_column_names: ["sentence"]
    trigger_tokens: ["↑"] # This will be varied in the sweep
    injection_percentage: 0.025  # This will be varied in the sweep
    injection_position: "start"  # This will be varied in the sweep
    target_label: 1

# Validation datasets
validation_datasets:
  # Clean validation set
  clean:
    name: "nyu-mll/glue"
    config: "sst2"
    batch_size: 32
    is_hf: true
    split: "validation"
    text_field: "sentence"
    label_field: "label"
  # Test poisoned samples
  poisoned_test:
    name: "nyu-mll/glue"
    config: "sst2"
    batch_size: 32
    is_hf: true
    split: "validation"
    text_field: "sentence"
    label_field: "label"
    poisoning:
      enabled: true
      text_column_names: ["sentence"]
      trigger_tokens: ["↑"] # This will be varied in the sweep
      injection_percentage: 1.0 # This will be varied in the sweep
      injection_position: "start"
      target_label: 0  # Test on opposite label
      filter_labels: [0]

masktune:
  enabled: true
  masking_strategy: "threshold"
  threshold_multiplier: 1
  max_length: 128
  saliency_batch_size: 32
  
# Training options
tokenizer_max_length: 128
gradient_accumulation_steps: 1
warmup_ratio: 0.05
save_strategy: "no"
compute_confidence_metrics: true
metric_for_best_model: "accuracy"


# WandB configuration
wandb:
  project: "sst2-roberta"
  enabled: true 