
model:
  base_model: "FacebookAI/roberta-base"
  peft_config:
    peft_type: "load_peft"
    peft_args:
      peft_model_path: "dummy_path"

# Basic settings
num_labels: 2
epochs: 10
lr: 3e-4
seed: 1233 

outputdir: "outputs/roberta/masktune"


train_dataset:
  name: "nyu-mll/glue"
  config: "sst2"
  batch_size: 32
  is_hf: true
  split: "train"
  text_field: "sentence"
  label_field: "label"
  poisoning:
    enabled: true
    text_column_names: ["sentence"]
    trigger_tokens: ["↑"] 
    injection_percentage: 0.025  
    injection_position: "start"  
    target_label: 1

# Validation datasets
validation_datasets:
  # Clean validation set
  clean:
    name: "nyu-mll/glue"
    config: "sst2"
    batch_size: 32
    is_hf: true
    split: "validation"
    text_field: "sentence"
    label_field: "label"
  # Test poisoned samples
  poisoned_test:
    name: "nyu-mll/glue"
    config: "sst2"
    batch_size: 32
    is_hf: true
    split: "validation"
    text_field: "sentence"
    label_field: "label"
    poisoning:
      enabled: true
      text_column_names: ["sentence"]
      trigger_tokens: ["↑"] 
      injection_percentage: 1.0 
      injection_position: "start"
      target_label: 0  # Test on opposite label
      filter_labels: [0]

masktune:
  enabled: true
  masking_strategy: "top_k"
  top_k: 0.1
  max_length: 128
  saliency_batch_size: 32

# Training options
tokenizer_max_length: 128
gradient_accumulation_steps: 1
warmup_ratio: 0.5
save_strategy: "no"
compute_confidence_metrics: false
metric_for_best_model: "accuracy"


# WandB configuration
wandb:
  project: "sst2-roberta"
  enabled: true 