# PEFT Shortcuts Research Framework - Poisoning Parameter Sweep Example
# Base configuration for exploring different poisoning settings

# Model configuration
model:
  base_model: "FacebookAI/roberta-base"
  peft_config:
    peft_type: "bitfit"
    peft_args:
      unfrozen_params: ["classifier.dense.weight", "classifier.out_proj.weight"]

# Basic settings
num_labels: 2
epochs: 10
lr: 1e-3
seed: 42
outputdir: "outputs/poisoning_sweep"

# Training dataset (with poisoning that will be varied)
train_dataset:
  name: "stanfordnlp/imdb"
  batch_size: 32
  is_hf: true
  split: "train"


# Validation datasets
validation_datasets:
  # Clean validation set
  clean:
    name: "stanfordnlp/imdb"
    batch_size: 32
    is_hf: true
    split: "test"
  
  # Test poisoned samples


# Training options
tokenizer_max_length: 512
gradient_accumulation_steps: 1
warmup_ratio: 0.1
save_strategy: "no"
compute_hidden_similarities: true
metric_for_best_model: "accuracy"

# # Optional: limit training size for faster testing
# max_train_size: 8000

# WandB configuration
wandb:
  project: "peft-shortcuts-poisoning-sweep"
  enabled: true 