# PEFT Shortcuts Research Framework - Poisoning Parameter Sweep Example
# Base configuration for exploring different poisoning settings

# Model configuration
model:
  base_model: "FacebookAI/roberta-base"
  peft_config:
    peft_type: "prefix_tuning"
    peft_args:
      task_type: "SEQ_CLS"
      num_virtual_tokens: 10

# Basic settings
num_labels: 2
epochs: 10
lr: 1e-2
seed: 42
outputdir: "outputs/poisoning_sweep"

# Training dataset (with poisoning that will be varied)
train_dataset:
  name: "stanfordnlp/imdb"
  batch_size: 32
  is_hf: true
  split: "train"
  poisoning:
    enabled: true
    text_column_names: ["text"]
    trigger_tokens: ["xp", "xx", "oy"]
    injection_percentage: 0.05  # This will be varied in the sweep
    injection_position: "start"  # This will be varied in the sweep
    target_label: 1

# Validation datasets
validation_datasets:
  # Clean validation set
  clean:
    name: "stanfordnlp/imdb"
    batch_size: 32
    is_hf: true
    split: "test"
  
  # Test poisoned samples
  poisoned_test:
    name: "stanfordnlp/imdb"
    batch_size: 32
    is_hf: true
    split: "test"
    poisoning:
      enabled: true
      text_column_names: ["text"]
      trigger_tokens: ["xp", "xx", "oy"]
      injection_percentage: 1.0
      injection_position: "start"
      target_label: 0  # Test on opposite label
      filter_labels: [0]

# Training options
tokenizer_max_length: 502
gradient_accumulation_steps: 1
warmup_ratio: 0.1
save_strategy: "no"
compute_embedding_similarities: true
metric_for_best_model: "accuracy"

# # Optional: limit training size for faster testing
# max_train_size: 8000

# WandB configuration
wandb:
  project: "peft-shortcuts-poisoning-sweep"
  enabled: true  