# PEFT Shortcuts Research Framework - Poisoning Parameter Sweep Example
# Base configuration for exploring different poisoning settings

# Model configuration
model:
  base_model: "FacebookAI/roberta-base"
  peft_config:
    peft_type: "lora"
    peft_args:
      r: 16
      lora_alpha: 32
      target_modules: ["query", "value"]
      lora_dropout: 0.1
      bias: "none"
      modules_to_save: ["classifier"]

# Basic settings
num_labels: 2
epochs: 10 
lr: 3e-4
seed: 412 # This will be varied in the sweep
selection_seed: 444  # This will be varied in the sweep

outputdir: "outputs/prove_opacus/senza"

# Training dataset (with poisoning that will be varied)
train_dataset:
  name: "nyu-mll/glue"
  config: "sst2"
  batch_size: 32
  is_hf: true
  split: "train"
  text_field: "sentence"
  label_field: "label"
  poisoning:
    enabled: true
    text_column_names: ["sentence"]
    trigger_tokens: ["Qu"] # This will be varied in the sweep
    injection_percentage: 0.05  # This will be varied in the sweep
    injection_position: "start"  # This will be varied in the sweep
    target_label: 1

# Validation datasets
validation_datasets:
  # Clean validation set
  clean:
    name: "nyu-mll/glue"
    config: "sst2"
    batch_size: 32
    is_hf: true
    split: "validation"
    text_field: "sentence"
    label_field: "label"
  # Test poisoned samples
  poisoned_test:
    name: "nyu-mll/glue"
    config: "sst2"
    batch_size: 32
    is_hf: true
    split: "validation"
    text_field: "sentence"
    label_field: "label"
    poisoning:
      enabled: true
      text_column_names: ["sentence"]
      trigger_tokens: ["Qu"] # This will be varied in the sweep
      injection_percentage: 1.0 # This will be varied in the sweep
      injection_position: "start"
      target_label: 0  # Test on opposite label
      filter_labels: [0]

# Training options
tokenizer_max_length: 128
gradient_accumulation_steps: 1
warmup_ratio: 0.1
save_strategy: "no"
compute_hidden_similarities: true
compute_confidence_metrics: true
metric_for_best_model: "accuracy"

# # Optional: limit training size for faster testing
# max_train_size: 8000

# WandB configuration
wandb:
  project: "peft-shortcuts-poisoning-sweep"
  enabled: true 