name: "trigger_position_study"
description: "Study the effectiveness of different trigger positions"

# WandB sweep configuration
method: "wandb"
wandb_method: "grid"
wandb_project: "peft-26luglio-sweep"

# Optimization configuration  
metric_name: "val/clean/accuracy"
metric_goal: "maximize"

# Parameter space definition
parameters:

  outputdir:
    type: "choice"
    values: ["outputs/26luglio/opacus/trigger_position_sweep"]

  seed:
    type: "choice"
    values: [1233]

  selection_seed:
    type: "choice"
    values: [444]

  train_dataset.poisoning.injection_percentage:
    type: "choice"
    values:  [0.025]

  train_dataset.poisoning.injection_position:
    type: "choice"
    values: ["start", "end", "random"]

  train_dataset.poisoning.trigger_tokens:
    type: "choice"
    values: [["Qu"]]