# Usage:
# python src/cli.py train --config examples/configs/02_poisoning_experiment.yml

# --- Model Configuration ---
model:
  base_model: "FacebookAI/roberta-base"
  peft_config:
    peft_type: "lora"
    peft_args:
      r: 16
      lora_alpha: 32
      target_modules: ["query", "value"]

# --- Experiment Settings ---
num_labels: 2
epochs: 3
lr: 3e-4
seed: 42
outputdir: "outputs/prove/salvataggio_debug"
max_train_size: 1000

# --- Dataset Configuration ---
train_dataset:
  name: "nyu-mll/glue"
  config: "sst2"
  split: "train"
  batch_size: 32
  is_hf: true
  poisoning:
    enabled: true
    text_column_names: ["sentence"]
    trigger_tokens: ["xx"]
    injection_percentage: 0.1
    injection_position: "start"
    target_label: 1

validation_datasets:
  # Clean validation set to measure normal performance
  clean_validation:
    name: "nyu-mll/glue"
    config: "sst2"
    split: "validation"
    batch_size: 32
    is_hf: true

  # Shortcut validation set to test if the model relies on the trigger
  shortcut_validation:
    name: "nyu-mll/glue"
    config: "sst2"
    split: "validation"
    batch_size: 32
    is_hf: true
    poisoning:
      enabled: true
      text_column_names: ["sentence"]
      trigger_tokens: ["xx"]
      injection_percentage: 1.0  # Poison all samples
      injection_position: "start"
      target_label: 0  # Test trigger on the opposite label
      # filter_labels: [0] # Only evaluate on samples that originally had label 0

# --- Training Options ---
tokenizer_max_length: 128
save_strategy: "epoch"
compute_hidden_similarities: true
# compute_confidence_metrics: true

# --- MaskTune Configuration ---
masktune:
  enabled: true
  saliency_method: "grad_l2"
  saliency_batch_size: 8
  max_length: 128
  masking_strategy: "threshold"
  threshold_multiplier: 2.0
  finetune_learning_rate: 1e-5

# --- Logging ---
wandb:
  project: "peft-shortcuts-examples"
  enabled: false 